Added registry async handler
egovernments/DIVOC pull request #1169
Opened 2022-07-24 18:19 UTC by ajay-beehyv

@prasanna-egov @saiprakash-v @egov-joy

2022-07-25 04:40 UTC, prasanna-egov requested changes
Docker compose entry is missing. Dockerfile and Makefile are missing. Add those as well.

2022-07-25 04:40 UTC, prasanna-egov commented on backend/registry-async-handler/main.js
> +        clientId: 'async-handler',
Registry Async Handler please

2022-07-25 04:40 UTC, prasanna-egov commented on backend/registry-async-handler/main.js
> +async function init_postCreateEntity_consumer(conf,kafka){
be consistent either use camelCase or _, don't mix

2022-07-25 04:40 UTC, prasanna-egov commented on backend/registry-async-handler/main.js
> +      if(certificateOsidMessage.entityType == conf.CERTIFICATE_ENTITY_TYPE){
Where is this conf from

2022-07-25 04:40 UTC, prasanna-egov commented on backend/registry-async-handler/main.js
> +          const certificateOsidMapResponse = await  axios.post(`${conf.SUNBIRD_CERTIFICATE_URL}${entityType}`, JSON.parse(message.value.toString()),
move to services folder. Follow similar forlder structure as other microservices.

2022-07-25 04:40 UTC, prasanna-egov commented on backend/registry-async-handler/package.json
> +    "axios": "^0.21.1",
use latest version of axios

2022-07-25 04:57 UTC, egov-joy commented
@ajay-beehyv please mention the story number in the commit message

2022-07-25 05:06 UTC, prasanna-egov commented
There are a lot of changes that are needed. Env variables need to move to config file. Main file need not have a module exports. I am sure this entire thing is not working. Could you do dev testing before raising the PR.

2022-07-28 12:14 UTC, ajay-beehyv commented
@prasanna-egov @egov-joy @saiprakash-v 
 This PR containes registry-async-handler microservice, schema for transactionOsidMap, APi to get osid from tranactionId in vc-management-service.
Removed divoc listener from this PR to reduce complexity and added new issue for it (HLM-477)

2022-07-30 06:05 UTC, saiprakash-v commented on backend/vc-management-service/src/configs/config.js
> +const STORED_ENTITY_TYPE = process.env.STORED_ENTITY_TYPE ;
This is just a table name. Can't we have it as a constant and not config?

2022-08-01 04:14 UTC, prasanna-egov commented on backend/vc-management-service/src/services/sunbird.service.js
> +        id:  "sunbird-rc.registry.search",
Move to constants

2022-08-01 06:42 UTC, prasanna-egov commented on backend/vc-management-service/src/services/sunbird.service.js
> +        ets: "",
What is this ets.

2022-08-01 07:06 UTC, ajay-beehyv commented on backend/vc-management-service/src/services/sunbird.service.js
> +        ets: "",
used that approach fron divoc/certificate-api, I'll test if all those variable are necessary

2022-08-01 11:52 UTC, ajay-beehyv commented on backend/vc-management-service/src/services/sunbird.service.js
> +        ets: "",
Removed unnecessary field from Transaction Request

2022-08-01 13:46 UTC, ajay-beehyv commented
> Docker compose entry is missing. Dockerfile and Makefile are missing. Add those as well.

resolved

2022-08-02 03:46 UTC, merged