HLM - 325 | Create new consumer in notificaion-service to accept raw messages
egovernments/DIVOC pull request #1187
Opened 2022-08-09 13:57 UTC by ajay-beehyv

@prasanna-egov @egov-joy @egov-joy

2022-08-09 14:39 UTC, saiprakash-v requested changes

2022-08-09 14:39 UTC, saiprakash-v commented on backend/notification-service/pkg/consumers/notify_consumer.go
> +						if err != nil {
You can do this err!=nil thing at the end of the above line itself.
`contactType, err := services.GetContactType(recipient); err != nil {...}`
Something like this. Please change it in all the places.

2022-08-09 14:39 UTC, saiprakash-v commented on backend/notification-service/pkg/consumers/notify_consumer.go
> +				log.Errorf("Error in committing notify2 message %+v", err)
Please change `notify2`

2022-08-10 05:48 UTC, varadeth approved these changes

2022-08-10 05:48 UTC, varadeth commented on backend/notification-service/pkg/consumers/notify_consumer.go
> +							log.Errorf("Invalid notification mobile number %+v, %+v", request, err)
should be Invalid notification email address

2022-08-10 06:18 UTC, prasanna-egov commented on backend/notification-service/pkg/consumers/notify_consumer.go
> +							log.Errorf("Invalid notification mobile number %+v, %+v", request, err)
I don't see this change is it done?

2022-08-10 06:21 UTC, merged