HLM-540 | Add validations to certification endpoint
egovernments/DIVOC pull request #1205
Opened 2022-08-23 19:11 UTC by vishwajeet-eGov

@srprasanna @varadeth Please review.

2022-08-24 06:14 UTC, varadeth commented on backend/vc-certification-service/src/services/validation.service.js
> +   if(isValid!= "valid"){
use !==

2022-08-24 06:14 UTC, varadeth commented on backend/vc-certification-service/src/controllers/certificate.controller.js
> +        const isValidPayload = validationService.validateCertificateInput(req);
instead of returning error in message format, can we throw error from validateCertificateInput. In that way, we wont need if else cases and let catch block handle the error objects thrown
error objects can contain statusCode of 400 and then appropriate message.
eg:
```
err = {
    response: {
          status: 400,
          data: "some error"
    }
}

2022-08-24 06:14 UTC, varadeth commented on backend/vc-certification-service/tests/certificate.controller.test.js
> +   console.log = jest.fn()
indentation

2022-08-24 06:14 UTC, varadeth commented on backend/vc-certification-service/tests/certificate.controller.test.js
> +    //const response = await certificateController.updateCertificate.mockImplementation(() => {throw new Error('some problem');});
remove this commented line

2022-08-24 07:58 UTC, saiprakash-v requested changes

2022-08-24 07:58 UTC, saiprakash-v commented on backend/vc-certification-service/src/services/validation.service.js
> +   {
Can you please fix all the lint issues? (Keep curly braces next to If statement parantheses and "else if's" followed after closing if "}" and proper spacing between if keywords and conditions etc)

2022-08-24 07:58 UTC, saiprakash-v commented on backend/vc-certification-service/src/services/validation.service.js
> +
As soon as one of the conditions fail, we can return the function right? No need to check all the other things

2022-08-24 16:24 UTC, prasanna-egov commented on backend/vc-certification-service/src/services/validation.service.js
> +function isURIFormat(param) {
Does this work for DID format as well. Did you validate?

2022-08-24 16:24 UTC, prasanna-egov commented on backend/vc-certification-service/src/services/validation.service.js
> +  return "valid";
You should return a boolean value

2022-08-25 06:59 UTC, saiprakash-v commented on backend/vc-certification-service/src/services/validation.service.js
> +    isValid = "Issued on date is missing"
Doing similar validations as the above function right? we can maintain consistent code practice. Pass in `err` object to this function as well and throw errors

2022-08-25 08:44 UTC, vishwajeet-eGov commented on backend/vc-certification-service/src/services/validation.service.js
> +    isValid = "Issued on date is missing"
Resolved

2022-08-25 08:45 UTC, vishwajeet-eGov commented on backend/vc-certification-service/src/services/validation.service.js
> +  return "valid";
Resolved

2022-08-25 08:45 UTC, vishwajeet-eGov commented on backend/vc-certification-service/src/services/validation.service.js
> +function isURIFormat(param) {
Resolved, test cases added.

2022-08-25 08:54 UTC, saiprakash-v approved these changes

2022-08-25 09:04 UTC, merged