HLM-574 | Create verification service
egovernments/DIVOC pull request #1223
Opened 2022-09-02 14:20 UTC by ajay-beehyv

@prasanna-egov @saiprakash-v @varadeth

2022-09-06 01:07 UTC, prasanna-egov commented on backend/vc-certification-service/src/controllers/certificate.controller.js
> +async function verifyCertificate (req,res){
Smaller methods

2022-09-07 05:55 UTC, varadeth requested changes

2022-09-07 05:55 UTC, varadeth commented on backend/vc-certification-service/src/controllers/certificate.controller.js
> +async function getCertificates(certificateId,certificateEntityType,token){
getRevokeCertificates and getCertificates does a similar thing. can this be refactored to a single function

2022-09-07 05:55 UTC, varadeth commented on backend/vc-certification-service/src/controllers/certificate.controller.js
> +            const certificateResponse = await getCertificates(certificateId,certificateEntityType,token);
why is getCertificates needed? Since it is verified, it means it has been signed using out private key and hence it is also stored in registry
we already have certificateId. Using that, we can pull in from RevokedVC for that certificateId

2022-09-07 10:21 UTC, ajay-beehyv commented on backend/vc-certification-service/src/controllers/certificate.controller.js
> +            const certificateResponse = await getCertificates(certificateId,certificateEntityType,token);
Certificate can be soft deleted from the entity, so we are checking it.

2022-09-07 11:19 UTC, saiprakash-v approved these changes

2022-09-07 12:33 UTC, prasanna-egov approved these changes

2022-09-07 12:33 UTC, merged