HLM-579 | Update context API
egovernments/DIVOC pull request #1227
Opened 2022-09-06 11:16 UTC by ajay-beehyv

@prasanna-egov @saiprakash-v @varadeth

2022-09-06 12:52 UTC, varadeth requested changes

2022-09-06 12:52 UTC, varadeth commented on backend/vc-management-service/src/configs/constants.js
> +const SUNBIRD_GET_CONTEXT_URL = `${config.SUNBIRD_REGISTRY_URL}/api/v1/ContextURL/`;
this is already present with MINIO_CONTEXT_URL

2022-09-06 12:52 UTC, varadeth commented on backend/vc-management-service/package.json
> +    "minio": "^7.0.32",
is this getting duplicated?
please check same with redis too

2022-09-06 12:52 UTC, varadeth commented on backend/vc-management-service/src/configs/config.js
> +    TENANT_NAME,
similar with this as well. is this duplicated?

2022-09-06 12:52 UTC, varadeth commented on backend/vc-management-service/src/services/sunbird.service.js
> +    console.log(constants.SUNBIRD_GET_CONTEXT_URL + osid );
after merge of PR #1228 this function will look different. Please get that merged properly

2022-09-06 12:52 UTC, varadeth commented on backend/vc-management-service/src/controllers/context.controller.js
> +        if(filename != getContextResp.url){
why is this required?
and even if this is required, please use !== instead of !=

2022-09-06 13:00 UTC, ajay-beehyv commented on backend/vc-management-service/src/configs/config.js
> +    TENANT_NAME,
They araised while resolving merge conflicts

2022-09-07 05:01 UTC, varadeth approved these changes

2022-09-08 06:18 UTC, saiprakash-v approved these changes

2022-09-08 06:24 UTC, merged