Generate token page
egovernments/DIVOC pull request #1308
Opened 2022-11-04 11:19 UTC by bhanuprakash-egov

@prasanna-egov @saiprakash-v

2022-11-10 02:11 UTC, saiprakash-v requested changes

2022-11-10 02:11 UTC, saiprakash-v commented on tenant-portal/public/locales/hi/translation.json
>          "title": "DIVOC VC Issuance Platform में आपका स्वागत है",
Translate this too

2022-11-10 02:11 UTC, saiprakash-v commented on tenant-portal/src/components/GenerateToken/GenerateToken.js
> +      return axios.get(`http://localhost/vc-management/v1/tenant/generatetoken/${userId}`).then(res =>
move this out to constants file

2022-11-15 04:20 UTC, saiprakash-v approved these changes

2022-11-15 06:17 UTC, prasanna-egov approved these changes

2022-11-15 06:17 UTC, merged