test and publish
egovernments/DIVOC pull request #1371
Opened 2022-12-15 03:53 UTC by bhanuprakash-egov

2022-12-15 23:07 UTC, bhanuprakash-egov commented
@saiprakash-v @prasanna-egov

2022-12-19 02:53 UTC, saiprakash-v requested changes

2022-12-19 02:53 UTC, saiprakash-v commented on tenant-portal/src/components/TestAndPublish/TestAndPublish.js
> +    // const schema = {
remove the comments

2022-12-19 02:53 UTC, saiprakash-v commented on tenant-portal/src/components/TestAndPublish/TestAndPublish.js
> +            // template:"Tenant/969b7d5c-4c2a-42a2-9d8f-5cd1348cf54d/templates/documents/527f7650-a8d0-42ae-a480-f01b9396bf72-trainingCert.html",
same here

2022-12-19 02:53 UTC, saiprakash-v commented on tenant-portal/src/components/TestAndPublish/TestAndPublish.js
> +        axios.post('/vc-management/v1/schema', schema, {headers:{Authorization:{userToken}}})
keep all the urls in one place

2022-12-19 02:53 UTC, saiprakash-v commented on tenant-portal/src/components/TestAndPublish/TestAndPublish.js
> +        return axios.post(`/vc-management/v1/schema/preview`, previewReqBody,
move urls to one place

2022-12-19 02:53 UTC, saiprakash-v commented on tenant-portal/src/components/TestAndPublish/TestAndPublish.js
> +            <h1>Test & Publish</h1>
Add translations

2022-12-19 03:59 UTC, saiprakash-v commented on tenant-portal/src/components/TestAndPublish/TestAndPublish.js
> +    const getToken = async () => {
can these be moved to keycloak utils?

2022-12-19 05:22 UTC, saiprakash-v approved these changes

2022-12-19 10:21 UTC, merged