Facility upload header validaiton
egovernments/DIVOC pull request #147
Opened 2021-01-06 09:19 UTC by burhanrashid52

2021-01-07 09:40 UTC, dileepbapat requested changes

2021-01-08 19:27 UTC, dileepbapat requested changes

2021-01-08 19:27 UTC, dileepbapat commented on backend/portal_api/pkg/db/db.go
> +	// status
avoid such comments that doesnt add additional information like //status. Field itself is status

2021-01-08 19:27 UTC, dileepbapat commented on backend/portal_api/pkg/handler.go
> +	if data.Text("facilityCode") == "" {
Put list of required fields and loop over it and validate.

2021-01-08 19:27 UTC, dileepbapat commented on backend/portal_api/pkg/handler.go
> +	preferredUsername := getUserName(params.HTTPRequest)
You dont need get Username as principal is already there in arg.  May be you might have found reference elsewhere when the principal model was not there. We should clean up that too

2021-01-09 03:10 UTC, burhanrashid52 commented on backend/portal_api/pkg/handler.go
> +	if data.Text("facilityCode") == "" {
Yup. Make more sense. Will do the changes.

2021-01-11 02:15 UTC, burhanrashid52 commented on backend/portal_api/pkg/handler.go
> +	log.Println(params.File)
Done

2021-01-11 02:15 UTC, burhanrashid52 commented on backend/portal_api/pkg/handler.go
> +		_ = createFacility(&data, params.HTTPRequest.Header.Get("Authorization"))
Done

2021-01-11 02:44 UTC, burhanrashid52 commented
This PR is a subset of #151 . Fix the review comment in #151 . Hence closing this PR

2021-01-11 02:44 UTC, closed without merging